# Generated by Django 2.2.5 on 2020-06-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200627_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='program_name',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
