# Generated by Django 2.2.5 on 2020-06-27 17:30

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200627_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='file',
            field=models.FileField(upload_to=app.models.get_upload_path),
        ),
    ]
