# Generated by Django 2.2.5 on 2020-06-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200627_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='alwaysRunning',
            field=models.BooleanField(default=False),
        ),
    ]
