# Generated by Django 2.2.5 on 2020-06-27 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_program_alwaysrunning'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='alwaysRunning',
            new_name='always_running',
        ),
    ]
