# Generated by Django 2.2.5 on 2020-06-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200627_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='git',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
