# Generated by Django 2.2.5 on 2020-06-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_program_git'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='custome_command',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
